name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SOLUTION_FILE_PATH: ./devops
  BUILD_CONFIGURATION: Debug
  SONAR_WRAPPER_URL: https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
  SONAR_SCANNER_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-windows.zip
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[,16.8]'
    
    - name: Cache build wrapper & SonarScanner
      id: cache-sonar
      uses: actions/cache@v2
      with:
        path: .\.sonar
        key: ${{ runner.os }}-sonar

    - name: Install SonarScanner
      if: steps.cache-sonar.outputs.cache-hit != 'true'
      run: |
        New-Item -Path .\.sonar -ItemType Directory
        Invoke-WebRequest -Uri "${{ env.SONAR_WRAPPER_URL }}" -OutFile .\.sonar\build-wrapper.zip
        Invoke-WebRequest -Uri "${{ env.SONAR_SCANNER_URL }}" -OutFile .\.sonar\sonar-scanner.zip
        Expand-Archive .\.sonar\build-wrapper.zip .\sonar
        Expand-Archive .\.sonar\sonar-scanner.zip .\sonar

    - name: Build
      run: |
        .\.sonar\build-wrapper-win-x86\build-wrapper-win-x86-64.exe --out-dir bw_output msbuild -m -p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Run SonarScanner        
      run: |
        .\.sonar\sonar-scanner-4.5.0.2216-windows\bin\sonar-scanner.bat -D sonar.login="${{secrets.SONAR_TOKEN}}" -D sonar.cfamily.build-wrapper-output=./bw_output -D sonar.host.url="https://sonarcloud.io"
